write("       A", '')
write("      B B", '')
write("     C   C", '')
write("    D     D", '')
write("   E       E", '')
write("    D     D", '')
write("     C   C", '')
write("      B B", '')
write("       A", '')