write("<AMO FAZER EXERCICIO NO URI>", '')
write("<    AMO FAZER EXERCICIO NO URI>", '')
write("<AMO FAZER EXERCICIO >", '')
write("<AMO FAZER EXERCICIO NO URI>", '')
write("<AMO FAZER EXERCICIO NO URI    >", '')
write("<AMO FAZER EXERCICIO NO URI>", '')
write("<          AMO FAZER EXERCICIO >", '')
write("<AMO FAZER EXERCICIO           >", '')