(def n (read-string (read-line)))
(printf "1 x %d = %d\n" n (* n 1))
(printf "2 x %d = %d\n" n (* n 2))
(printf "3 x %d = %d\n" n (* n 3))
(printf "4 x %d = %d\n" n (* n 4))
(printf "5 x %d = %d\n" n (* n 5))
(printf "6 x %d = %d\n" n (* n 6))
(printf "7 x %d = %d\n" n (* n 7))
(printf "8 x %d = %d\n" n (* n 8))
(printf "9 x %d = %d\n" n (* n 9))
(printf "10 x %d = %d\n" n (* n 10))