Printf.printf "---------------------------------------\n";
Printf.printf "|  decimal  |  octal  |  Hexadecimal  |\n";
Printf.printf "---------------------------------------\n";
Printf.printf "|      0    |    0    |       0       |\n";
Printf.printf "|      1    |    1    |       1       |\n";
Printf.printf "|      2    |    2    |       2       |\n";
Printf.printf "|      3    |    3    |       3       |\n";
Printf.printf "|      4    |    4    |       4       |\n";
Printf.printf "|      5    |    5    |       5       |\n";
Printf.printf "|      6    |    6    |       6       |\n";
Printf.printf "|      7    |    7    |       7       |\n";
Printf.printf "|      8    |   10    |       8       |\n";
Printf.printf "|      9    |   11    |       9       |\n";
Printf.printf "|     10    |   12    |       A       |\n";
Printf.printf "|     11    |   13    |       B       |\n";
Printf.printf "|     12    |   14    |       C       |\n";
Printf.printf "|     13    |   15    |       D       |\n";
Printf.printf "|     14    |   16    |       E       |\n";
Printf.printf "|     15    |   17    |       F       |\n";
Printf.printf "---------------------------------------\n";