main :: IO ()
main = do
    putStrLn $ "---------------------------------------"
    putStrLn $ "|  decimal  |  octal  |  Hexadecimal  |"
    putStrLn $ "---------------------------------------"
    putStrLn $ "|      0    |    0    |       0       |"
    putStrLn $ "|      1    |    1    |       1       |"
    putStrLn $ "|      2    |    2    |       2       |"
    putStrLn $ "|      3    |    3    |       3       |"
    putStrLn $ "|      4    |    4    |       4       |"
    putStrLn $ "|      5    |    5    |       5       |"
    putStrLn $ "|      6    |    6    |       6       |"
    putStrLn $ "|      7    |    7    |       7       |"
    putStrLn $ "|      8    |   10    |       8       |"
    putStrLn $ "|      9    |   11    |       9       |"
    putStrLn $ "|     10    |   12    |       A       |"
    putStrLn $ "|     11    |   13    |       B       |"
    putStrLn $ "|     12    |   14    |       C       |"
    putStrLn $ "|     13    |   15    |       D       |"
    putStrLn $ "|     14    |   16    |       E       |"
    putStrLn $ "|     15    |   17    |       F       |"
    putStrLn $ "---------------------------------------"