package main
 
import (
    "fmt"
)
 
func main() {
    fmt.Println("2")
    fmt.Println("4")
    fmt.Println("6")
    fmt.Println("8")
    fmt.Println("10")
    fmt.Println("12")
    fmt.Println("14")
    fmt.Println("16")
    fmt.Println("18")
    fmt.Println("20")
    fmt.Println("22")
    fmt.Println("24")
    fmt.Println("26")
    fmt.Println("28")
    fmt.Println("30")
    fmt.Println("32")
    fmt.Println("34")
    fmt.Println("36")
    fmt.Println("38")
    fmt.Println("40")
    fmt.Println("42")
    fmt.Println("44")
    fmt.Println("46")
    fmt.Println("48")
    fmt.Println("50")
    fmt.Println("52")
    fmt.Println("54")
    fmt.Println("56")
    fmt.Println("58")
    fmt.Println("60")
    fmt.Println("62")
    fmt.Println("64")
    fmt.Println("66")
    fmt.Println("68")
    fmt.Println("70")
    fmt.Println("72")
    fmt.Println("74")
    fmt.Println("76")
    fmt.Println("78")
    fmt.Println("80")
    fmt.Println("82")
    fmt.Println("84")
    fmt.Println("86")
    fmt.Println("88")
    fmt.Println("90")
    fmt.Println("92")
    fmt.Println("94")
    fmt.Println("96")
    fmt.Println("98")
    fmt.Println("100")
}