(println "       A")
(println "      B B")
(println "     C   C")
(println "    D     D")
(println "   E       E")
(println "    D     D")
(println "     C   C")
(println "      B B")
(println "       A")