(println "<AMO FAZER EXERCICIO NO URI>")
(println "<    AMO FAZER EXERCICIO NO URI>")
(println "<AMO FAZER EXERCICIO >")
(println "<AMO FAZER EXERCICIO NO URI>")
(println "<AMO FAZER EXERCICIO NO URI    >")
(println "<AMO FAZER EXERCICIO NO URI>")
(println "<          AMO FAZER EXERCICIO >")
(println "<AMO FAZER EXERCICIO           >")