main :: IO ()
main = do
    putStrLn $ "I=1 J=7"
    putStrLn $ "I=1 J=6"
    putStrLn $ "I=1 J=5"
    putStrLn $ "I=3 J=7"
    putStrLn $ "I=3 J=6"
    putStrLn $ "I=3 J=5"
    putStrLn $ "I=5 J=7"
    putStrLn $ "I=5 J=6"
    putStrLn $ "I=5 J=5"
    putStrLn $ "I=7 J=7"
    putStrLn $ "I=7 J=6"
    putStrLn $ "I=7 J=5"
    putStrLn $ "I=9 J=7"
    putStrLn $ "I=9 J=6"
    putStrLn $ "I=9 J=5"